### ISSUE TITLE
Errors while running

### ISSUE THREAD

**Issue by bharadwajdhornala** [czq142857/implicit-decoder#11]
Hi @czq142857 Thanks for the code. I have got any error while running the command from IMSVR **python main.py --train --epoch 200** . Error is
self.data_points = (self.data_points_int.astype(np.float32)+0.5)/256-0.5
MemoryError: Unable to allocate 6.41 GiB for an array with shape (35019, 16384, 3) and data type float32
Please guide. Thanks!!

**Comment by czq142857** [comment]
This issue is irrelevant to this repo, since there is no such line in my code:
self.data_points = (self.data_points_int.astype(np.float32)+0.5)/256-0.5

Please do not post irrelevant issues here.
