### ISSUE TITLE
quantitative evaluation of 3D shape generation

### ISSUE THREAD

**Issue by flyKite1998** [czq142857/implicit-decoder#16]
hi Zhiqin:
Thanks for your great work. And i am doing some works about  3D shape generation recently.I find that you show the results of COV-LFD and MMD-LFD in paper.Do you have the results of COV-CD or MMD-CD ? I would appreciate it if you could reply.

**Comment by czq142857** [comment]
Hi, I think I had them several years ago but I could not find them now. Anyway, CD is sensitive to normalization and the number of sampled points, so my numbers may not be correct in your setting. Please download the code and pretrained models and run it. It is very easy to run the shape generation code, and then you can evaluate the generated shapes in your setting.

**Comment by flyKite1998** [comment]
Thanks for your reply. I will follow your advice.
