### ISSUE TITLE
Light Field Descriptor

### ISSUE THREAD

**Issue by guyamir** [czq142857/implicit-decoder#3]
Hi Zhiqin,

Thanks for the great work.
Where can I find an implementation of the light field descriptor for model evaluation?

Best regards,
Guy

**Comment by czq142857** [comment]
The one I found is here:
https://github.com/Sunwinds/ShapeDescriptor/tree/master/LightField/3DRetrieval_v1.8/3DRetrieval_v1.8

The code is written in C and the executable only does shape retrieval (according to the matching scores). You might need to change some lines to get the actual scores and recompile the code.

Best,
Zhiqin
