### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by kemangjaka** [czq142857/implicit-decoder#4]
Hi! 
Thank you for providing the code! 
I'm so excited to see the presentation in CVPR 2019!

What kind of software (or package ?) to visualize generated 3D point cloud?
In other words, how did you create the demo video or the figures in the paper?

Thank you in advance for considering!

Cheers,

**Comment by czq142857** [comment]
Hi,

We did not generate point clouds.
The outputs are triangular meshes, and we use 3ds max to render those meshes.

Best,
Zhiqin

**Comment by kemangjaka** [comment]
ah, sorry. Thank you for the quick reply!
