### ISSUE TITLE
How to test the model on my own 3D voxelized shape?

### ISSUE THREAD

**Issue by rundiwu** [czq142857/implicit-decoder#6]
Hi, thanks for the code first. I want to try out the model on my own 3D voxelized shape for reconstruction. Is there any quick way to do this? Only training commands are provided in README.

Thanks!

**Comment by czq142857** [comment]
Hi. Please find the data preparation code in point_sampling directory. If you have .binvox data you could use the provided vox2pointvaluepair_from_binvox.py.

Best,
Zhiqin

**Comment by rundiwu** [comment]
Oh, so you mean for testing, point-value pairs are also needed?

**Comment by czq142857** [comment]
Point-value pairs are not required for testing. But the code does read the data as hdf5 files, so you need to convert the voxels into hdf5 as a preprocessing step.

Also, please pay attention to normalization. The pretrained models are trained on datasets normalized by setting the diagonal of the shape's bounding box to 1. If you use binvox you are likely to get another normalization by setting the longest edge in the shape's bounding box to 1.

**Comment by bharadwajdhornala** [comment]
Hi, @ChrisWu1997  @czq142857 .Thanks for the code. I am trying to test your code but README contains all training commands. I am testing on HSP dataset. Can I get the test commands.
Thanks!!
