### ISSUE TITLE
how can I make gif animation from a lot of .dae file?

### ISSUE THREAD

**Issue by tianyilt** [czq142857/implicit-decoder#9]
Hi,sincerely thank you for your great work.
Did you know how can I make gif animation from a lot of .dae file. 
I'm using the great work in bionic design related research and I need to use it to produce the Interpolation effect.
I try many dae viewer but they can just view one model one time.
one of author of the research say that he uses 3dmax in one issue and i guess it can be made by using 3dmax to make animation but i haven't taken it. I need more information about this.
thank you!

**Comment by czq142857** [comment]
Here is my pipeline of making those gifs.

1. Render 3D models to images. You may want to write a script to do it automatically.
2. Piece all rendered images together to make a video or gif.

Best,
Zhiqin

**Comment by tianyilt** [comment]
Thank you very much. I'm new in 3D file processing. I could render 3D voxel models to 2D image in same angle. But what confused me is that render mesh 3d file like .dae .stl in same angle. Could you provide some blog for this? I tried many terms to research in google but failed.

**Comment by czq142857** [comment]
You need to learn a 3D modeling or rendering software, such as 3DS max, Maya, Blender.

Best,
Zhiqin

**Comment by tianyilt** [comment]
thank you sincerely
